# WEEK-9 ASSESSMENT ON SQL, DATABASES, AND ETL

Question-1:What is DBMS?
##### Answer:DBMS stands for Database Management System.It is a software designed to store, retrieve, define, and manage data in a database.

Question-2: What is RDBMS?

###### Answer: RDBMS means Relational Database Management System. RDBMS stores data in a row-based table structure connecting related data elements. It is a program that allows you to create, update, and administer a relational database.

Question-3:What is SQL?
##### SQL means Structured Query Language,SQL is a standard language for storing, manipulating and retrieving data in databases,It used to communicate with a database.

Question-4:What is a Database?

##### Answer: A database is an organized collection of structured information, or data, typically stored electronically in a computer system.It is an organized collection of data, so that it can be easily accessed and managed.

Question-5:What are tables and Fields?
##### Answer: A table is a collection of related data held in a table format within a database. A table has records (rows) and fields (columns). Fields are columns.

Question-6:What is a primary key?
##### Answer:A primary key is the field (or fields) that is used to uniquely identify each record in a table. It is a unique identifier.

Question-7: What is a unique key?
##### Answer: A unique key is a group of one or more than one fields or columns of a table which uniquely identify database record. 

##### A unique key is the same as a primary key, however it can accept one null value for a table column. It is also called a unique constraint. A unique constraint can be used to ensure rows are unique within the database.

Question-8: What is a foreign key?
#####  A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables.

##### It is a set of attributes in a table that refers to the primary key of another table. The foreign key links these two tables.

Question-9:What is a join?
##### Answer: A join is an SQL operation performed to establish a connection between two or more database tables based on matching columns, thereby creating a relationship between the tables.  A JOIN is a means for combining fields from two tables by using values common to each.

Question-10: What are the types of join and explain each?
##### Answer types of joins includes;
A.INNER JOIN: This select and returns records that have matching values in both tables e.g
SELECT column_name(s)
FROM First_table1
INNER JOIN Second_table
ON First_table1.column_name = Second_table.column_name;

B.FULL (OUTER) JOIN: Returns all records when there is a match in either left or right table.

C.RIGHT (OUTER) JOIN: Returns all records from the right table (table2), and the matching records from the left table (table1). The result is 0 records from the left side, if there is no match.

D.LEFT (OUTER) JOIN: Returns all records from the left table (table1), and the matching records from the right table (table2). The result is 0 records from the right side, if there is no match.

F.SELF JOIN − is used to join a table to itself as if the table were two tables, temporarily renaming at least one table in the SQL statement.
CARTESIAN JOIN OR CROSS JOIN − returns the Cartesian product of the sets of records from the two or more joined tables.
G.The UNION operator is used to combine the result-set of two or more SELECT statements.

Every SELECT statement within UNION must have the same number of columns
The columns must also have similar data types
The columns in every SELECT statement must also be in the same order e.g

SELECT column_name(s) FROM First_table1
UNION
SELECT column_name(s) FROM Second_table;

Question-11:What is normalization?
##### Answers: Normalization is a process of organizing the data in database to avoid data redundancy, insertion anomaly, update anomaly & deletion anomaly. Normalization rules divides larger tables into smaller tables and links them using relationships. The purpose of Normalisation in SQL is to eliminate redundant (repetitive) data and ensure data is stored logically.

Question 12:What is Denormalization?
##### Answers: Denormalization is a database optimization technique where we add redundant data in the database to get rid of the complex join operations.
##### Denormalization is the process of trying to improve the read performance of a database, at the expense of losing some write performance, by adding redundant copies of data or by grouping data.

Question 13:What are all the different normalizations?
##### Answer: 
First Normal Form (1 NF)
Second Normal Form (2 NF)
Third Normal Form (3 NF)
Boyce Codd Normal Form or Fourth Normal Form ( BCNF or 4 NF)
Fifth Normal Form (5 NF)

Question 14:The normal forms can be divided into 5 forms, explain below.

##### Answers:
Normal Form	Description
1NF A relation is in 1NF if it contains an atomic value.

2NF A relation will be in 2NF if it is in 1NF and all non-key attributes are fully functional dependent on the primary key.

3NF A relation will be in 3NF if it is in 2NF and no transition dependency exists.

4NF A relation will be in 4NF if it is in Boyce Codd normal form and has no multi-valued dependency.

5NF A relation is in 5NF if it is in 4NF and not contains any join dependency and joining should be lossless.

Question 14: What is a View?
##### Answers: Views in SQL are kind of virtual tables. A view also has rows and columns as they are in a real table in the database. We can create a view by selecting fields from one or more tables present in the database. A View can either have all the rows of a table or specific rows based on certain condition.  A VIEW is simply a data object which contains no data. Its contents are the resultant of the base table. They are operated just like the base table but they don’t contain any data of their own.

Question 15:What is an Index?
##### Answer: The indexes are special objects which built on top of tables. The indexes can do an operation like SELECT, DELETE and UPDATE statement faster to manipulate a large amount of data. An INDEX can also be called a table and it has a data structure. An INDEX is created on columns of a table. One table may contain one or more INDEX tables.

Question 16A:. What are all the different types of indexes
##### Answers: These includes; Unique Index,Clustered Index,Non-Clustered Index

Question 16B:There are three types of indexes -List and explain?
##### Answer 
Clustered Index:
This index reorders the physical order of the table and searches based on the basis of key values. Each table can only have one clustered index.

Non-Clustered Index:

Non-Clustered Index does not alter the physical order of the table and maintains a logical order of the data. Each table can have many nonclustered indexes.

Unique Index:
This index does not allow the field to have duplicate values if the column is unique indexed. If a primary key is defined, a unique index can be applied automatically.

Question 17:What is a Cursor?
A cursor in SQL is a temporary work area created in system memory when a SQL statement is executed. A SQL cursor is a set of rows together with a pointer that identifies a current row. It is a database object to retrieve data from a result set one row at a time.

Question 18:What is a relationship and what are they?
##### Answer
Relationships are the established associations between two or more tables. Relationships are based on common fields from more than one table, often involving primary and foreign keys.


The major ones are; 

One to One Relationships,

One to Many and Many to One Relationships,

Many to Many Relationships,

Self Referencing Relationships(not so common,This is used when a table needs to have a relationship with itself.)

Question 19:What is a query
##### Answer
A query is a question or inquiry about a set of data. A query is a request for data or information from a database table or combination of tables. This data may be generated as results returned by Structured Query Language (SQL)

Question 20:What is subquery?
##### Answers: A Subquery or Inner query or a Nested query is a query within another SQL query and embedded within the WHERE clause. A subquery is used to return data that will be used in the main query as a condition to further restrict the data to be retrieved

Question 21:What are the types of subquery?
##### Answers: Types of Subqueries

Single Row Sub Query: Sub query which returns single row output,

Multiple row sub query: Sub query returning multiple row output,

Multiple columns sub query: Sub query returning one or more columns output,

Correlated Sub Query: Correlated subqueries depend on data provided by the outer query,

Nested subqueries: returns output for queries within a query(inner and outer query).

Question 22: What is a stored procedure?
A stored procedure is a prepared SQL code that is saved for reusability,the code can be reused over and over again. A Stored Procedure can be used as a modular programming which means create once, store and call for several times whenever it is required. This supports faster execution. It also reduces network traffic and provides better security to the data

Uses for stored procedures include data-validation or access-control mechanisms.

Question 23: What is a trigger?
##### Answer:  A SQL trigger is a database object which fires when an event occurs in a database. We can execute a SQL query that will "do something" in a database when a change occurs on a database table such as a record is inserted or updated or deleted.

A trigger is a special type of stored procedure that automatically runs when an event occurs in the database server.

Question 24":What is the difference between DELETE and TRUNCATE commands?
##### Answer:
DELETE is DML command and TRUNCATE is DDL command. DELETE deletes records one by one and makes an entry for each and every deletion in the transaction log, whereas The truncate command deletes rows by deallocating the pages.

Truncate always removes rows from a table,leaving the table empty and structure intact whereas delete may remove conditionally if the where clause is used. The rows deleted by Truncate statement cannot be restored and you cannot specify where clause in Truncate statment.

Question 25:
What are local and global variables and their differences?
##### Answers: Variables are classified into Global variables and Local variables based on their scope. The main difference between Global and local variables is that global variables can be accessed globally in the entire program, whereas local variables can be accessed only within the function or block in which they are defined.

Question 26: What is a constraint?
##### Answer:
SQL constraints are used to specify rules for the data in a table. Constraints are used to limit the type of data that can go into a table. Constraints can be column level or table level. Column level constraints apply to a column, and table level constraints apply to the whole table.

Constraints are simply the rules enforced on the data columns of a table. These are used to limit the type of data that can go into a table.

Question 27: What is data Integrity?
##### Answers: Data Integrity is used to maintain accuracy and consistency of data in a table. This can be implemented using constraints.

Question 28: What is Auto Increment?

 ##### Answers: Auto-increment allows a unique number to be generated automatically when a new record is inserted into a table. It allows us to automatically generate values in a numeric column upon row insertion.

Question 29: What is the difference between Cluster and Non-Cluster Index?

##### Answers: A Clustered index is a type of index in which table records are physically reordered to match the index. A Non-Clustered index is a special type of index in which logical order of index does not match physical stored order of the rows on disk. There can be only one clustered index per table while non clustered tables can have multiple indexes.

Question 30: What is Datawarehouse? 

##### Answers: In computing, a data warehouse, also known as an enterprise data warehouse, is a system used for reporting and data analysis and is considered a core component of business intelligence. Datawarehouse are central repositories of integrated data from one or more disparate sources.A data warehouse is a large collection of business data used to help an organization make decisions.

Question 31: What is Self-Join?

##### Answers: A self join is a join in which a table is joined with itself,example is when the table has a FOREIGN KEY which references its own PRIMARY KEY. To join a table itself means that each row of the table is combined with itself and with every other row of the table.

Question 32: What is Cross-Join? 
##### Answers: CROSS JOIN is used to combine each row of the first table with each row of the second table. It is also known as the Cartesian join since it returns the Cartesian product of the sets of rows from the joined tables,The CROSS JOIN is used to generate a paired combination of each row of the first table with each row of the second table.

Question 33: What is user defined functions?

##### Answers: A user-defined function is a function provided by the user of a program or environment, in a context where the usual assumption is that functions are built into the program or environment. UDFs are usually written for the requirement of its creator.

Question 34: What are all types of user defined functions?

##### Answers: There can be 4 different types of user-defined functions, they are:
Function with no arguments and no return value,

Function with no arguments and a return value,

Function with arguments and no return value,

Function with arguments and a return value.

Question 35: What is collation?

##### Answers: SQL Server collation refers to a set of character and character encoding rules, and influences how information is stored according to the order in the data page, how data is matched by comparing two columns, and how information is arranged in the T-SQL query statement.

##### Collation is a set of rules that tell database engine how to compare and sort the character data in SQL Server.

Question 36: What are all different types of collation sensitivity?Following are the different types of collation sensitivity:
##### Answers:
Case Sensitivity: A and a and B and b,

Kana Sensitivity: Japanese Kana characters,

Width Sensitivity: Single byte character and double-byte character,

Accent Sensitivity: This establishes whether it is accent sensitive or insensitive,

Variation-selector sensitivity:provide sorting rules, case, and accent sensitivity propperties.

Question 37: Advantages and Disadvantages of Stored Procedure?
##### Advantages includes;

It reduces network traffic.

It is reusable.

To help you build powerful database applications,enhances better performance, higher productivity, ease of use, and increased scalability.

Stored procedures enable you to take advantage of the computing resources of the server and 
access information to quickly solve problems and reduce downtime.

Make sure every employees is on the same page.

Reduce risk, improve security and quality.

It can help to be in compliance with norms/certifications.
 
##### Disadvantages includes;

Testability:Business logic which is encapsulated in stored procedures becomes very difficult to test.

Maintainability: They difficult to maintain

Debugging issues.

It is database dependent.

It is non-portable,

Question 38: What is Online Transaction Processing (OLTP)?

##### Answers: Online transaction processing (OLTP) is a class of systems that supports or facilitates high transaction-oriented applications. OLTP or Online Transaction Processing is a type of data processing that consists of executing a number of transactions occurring concurrently

Question 39: What is CLAUSE?
##### Answers: A clause in SQL is a part of a query that lets you filter or customizes how you want your data to be queried to you.

Question 40: What is recursive stored procedure?

##### Answers: Recursive stored procedure refers to a stored procedure which calls by itself until it reaches some boundary condition. This recursive function or procedure helps the programmers to use the same set of code n number of times.A stored procedure can be recursive, referencing itself directly or indirectly.

Question 41: what is Union, minus and Interact commands? 

##### Answers: UNION combines the two answer sets into a single answer set. It automatically removes duplicate rows from the result, 
###### MINUS gives you the rows that are found in the first query and not in the second query by removing from the results all the rows that are found only in the second query.

###### The SQL INTERSECT clause/operator is used to combine two SELECT statements, but returns rows only from the first SELECT statement that are identical to a row in the second SELECT statement. This means INTERSECT returns only common rows returned by the two SELECT statements.

Question 42A: What is an ALIAS command?

##### Answers: SQL aliases are used to give a table, or a column in a table, a temporary name. Aliases are often used to make column names more readable. An alias only exists for the duration of that query. An alias is created with the AS keyword.

Question 42B. ALIAS name can be given to a table or column. This alias name can be referred in WHERE clause to identify the table or column, Show.
##### Alias sample
SELECT column_name(s) FROM table_name AS alias_name
WHERE column_name(s) ='specification';

Question 43: What is the difference between TRUNCATE and DROP statements?
The DROP command is used to remove table definition and its contents. Whereas the TRUNCATE command is used to delete all the rows from the table.

Question 44: What are aggregate and scalar functions?

##### Answer: Aggregate functions operate against a collection of values and return a single summarizing value. Scalar functions return a single value based on scalar input arguments. Some scalar functions, such as CURRENT_TIME, do not require any arguments.

Question 45: How can you create an empty table from an existing table? 

##### Answer: A copy of an existing table can be created using a combination of the CREATE TABLE statement and the SELECT statement, To do this, the SQL CREATE TABLE syntax is: CREATE TABLE new_table AS (SELECT * FROM old_table WHERE 1=2);

Question 46: How to fetch common records from two tables? 
 you can use INNER JOIN,  UNION ALL

or INTERSECT

Question 47A: How to fetch alternate records from a table?
 To fetch every alternative row,  we use MOD() under WHERE. Then  we use ORDER BY DESC to display the result in descending order.

Question 47B. How do you display even numbers-.To select all the even number records from a table: Select * from table where id % 2 = 0. 
e.g 
SELECT * FROM Orders where OrderID % 2 = 0;;

Question 47C. How do you display odd numbers-.
##### Answer To select all the odd number records from a table: Select * from table where id % 2 != 0.

Question 48: How to select unique records from a table?

##### Answer: you can use this SQL statement: SELECT DISTINCT column_name FROM table_name;

Question 49: What is the command used to fetch first 5 characters of the string?

##### Answer: We use a statement like: Select SUBSTRING(StudentName,1,5) as studentname from student.

Question 50:Which operator is used in query for pattern matching?
LIKE operator is used for pattern matching, and it can be used as -. % – It matches zero or more characters